In [2]:
import numpy as np
import pandas as pd

PATH = r"..\..\data\household_power_consumption.txt"
df = pd.read_csv(PATH, sep = ";")
df

FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\data\\household_power_consumption.txt'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   object
 1   Time                   object
 2   Global_active_power    object
 3   Global_reactive_power  object
 4   Voltage                object
 5   Global_intensity       object
 6   Sub_metering_1         object
 7   Sub_metering_2         object
 8   Sub_metering_3         float64
dtypes: float64(1), object(8)
memory usage: 142.5+ MB

In [ ]:
df['Date'] = pd.to_datetime(df["Date"])
df['Time'] = pd.to_datetime(df['Time'])

C:\Users\admin\AppData\Local\Temp\ipykernel_5988\1570898981.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df["Date"])
C:\Users\admin\AppData\Local\Temp\ipykernel_5988\1570898981.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'])

In [ ]:
df["Datetime"] = pd.to_datetime(df["Date"], ' ',df['Time'], format='%d/%m/%Y %H:%M:%S')
df = df.set_index('Datetime')

In [ ]:
df

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,,,
2006-12-16,2006-12-16,2025-07-08 17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
2006-12-16,2006-12-16,2025-07-08 17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2006-12-16,2006-12-16,2025-07-08 17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
2006-12-16,2006-12-16,2025-07-08 17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
2006-12-16,2006-12-16,2025-07-08 17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
...,...,...,...,...,...,...,...,...,...
2010-11-26,2010-11-26,2025-07-08 20:58:00,0.946,0.0,240.43,4.0,0.0,0.0,0.0
2010-11-26,2010-11-26,2025-07-08 20:59:00,0.944,0.0,240.0,4.0,0.0,0.0,0.0
2010-11-26,2010-11-26,2025-07-08 21:00:00,0.938,0.0,239.82,3.8,0.0,0.0,0.0
2010-11-26,2010-11-26,2025-07-08 21:01:00,0.934,0.0,239.7,3.8,0.0,0.0,0.0
2010-11-26,2010-11-26,2025-07-08 21:02:00,0.932,0.0,239.55,3.8,0.0,0.0,0.0

In [ ]:
df.loc['2006-12-16']

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,,,
2006-12-16,2006-12-16,2025-07-08 17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
2006-12-16,2006-12-16,2025-07-08 17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2006-12-16,2006-12-16,2025-07-08 17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
2006-12-16,2006-12-16,2025-07-08 17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
2006-12-16,2006-12-16,2025-07-08 17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
...,...,...,...,...,...,...,...,...,...
2006-12-16,2006-12-16,2025-07-08 23:55:00,1.290,0.000,240.690,6.800,0.000,0.000,0.0
2006-12-16,2006-12-16,2025-07-08 23:56:00,2.730,0.060,239.430,11.400,0.000,1.000,0.0
2006-12-16,2006-12-16,2025-07-08 23:57:00,2.734,0.062,239.810,11.400,0.000,2.000,0.0
2006-12-16,2006-12-16,2025-07-08 23:58:00,2.764,0.066,241.270,11.400,0.000,1.000,0.0
2006-12-16,2006-12-16,2025-07-08 23:59:00,2.586,0.070,241.630,11.000,0.000,1.000,0.0

In [ ]:
df.resample('M').first()

C:\Users\admin\AppData\Local\Temp\ipykernel_5988\1152842028.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M').first()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,,,
2006-12-31,2006-12-16,2025-07-08 17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
2007-01-31,2007-01-01,2025-07-08 00:00:00,2.580,0.136,241.970,10.600,0.000,0.000,0.0
2007-02-28,2007-02-01,2025-07-08 00:00:00,0.326,0.128,243.150,1.400,0.000,0.000,0.0
2007-03-31,2007-03-01,2025-07-08 00:00:00,0.226,0.000,243.190,1.000,0.000,0.000,0.0
2007-04-30,2007-04-01,2025-07-08 00:00:00,3.480,0.238,239.530,14.400,2.000,1.000,18.0
2007-05-31,2007-05-01,2025-07-08 00:00:00,0.340,0.140,237.320,1.600,0.000,0.000,0.0
2007-06-30,2007-06-01,2025-07-08 00:00:00,0.408,0.196,236.960,1.800,0.000,2.000,0.0
2007-07-31,2007-07-01,2025-07-08 00:00:00,2.744,0.350,239.090,11.600,0.000,1.000,18.0
2007-08-31,2007-08-01,2025-07-08 00:00:00,0.102,0.000,235.860,0.400,0.000,0.000,0.0
2007-09-30,2007-09-01,2025-07-08 00:00:00,0.908,0.272,241.460,3.800,0.000,1.000,0.0
2007-10-31,2007-10-01,2025-07-08 00:00:00,1.324,0.000,239.040,5.400,0.000,0.000,17.0
2007-11-30,2007-11-01,2025-07-08 00:00:00,0.292,0.098,242.940,1.200,0.000,2.000,0.0
2007-12-31,2007-12-01,2025-07-08 00:00:00,0.318,0.102,244.300,1.400,0.000,0.000,0.0
2008-01-31,2008-01-01,2025-07-08 00:00:00,1.620,0.070,241.250,6.600,0.000,0.000,18.0
2008-02-29,2008-02-01,2025-07-08 00:00:00,2.268,0.184,239.790,9.400,0.000,0.000,18.0
2008-03-31,2008-03-01,2025-07-08 00:00:00,0.586,0.076,241.320,2.400,0.000,0.000,0.0
2008-04-30,2008-04-01,2025-07-08 00:00:00,1.356,0.000,243.870,5.400,0.000,0.000,18.0
2008-05-31,2008-05-01,2025-07-08 00:00:00,0.324,0.084,241.380,1.400,0.000,0.000,0.0
2008-06-30,2008-06-01,2025-07-08 00:00:00,1.050,0.342,242.330,4.600,0.000,0.000,1.0
2008-07-31,2008-07-01,2025-07-08 00:00:00,1.326,0.110,241.550,5.400,0.000,0.000,19.0
2008-08-31,2008-08-01,2025-07-08 00:00:00,0.500,0.226,239.750,2.400,0.000,0.000,1.0
2008-09-30,2008-09-01,2025-07-08 00:00:00,1.300,0.000,243.040,5.400,0.000,0.000,19.0
2008-10-31,2008-10-01,2025-07-08 00:00:00,0.352,0.098,243.940,1.400,0.000,0.000,1.0
2008-11-30,2008-11-01,2025-07-08 00:00:00,0.602,0.184,242.500,2.800,0.000,0.000,0.0
2008-12-31,2008-12-01,2025-07-08 00:00:00,0.514,0.138,245.290,2.400,0.000,0.000,0.0
2009-01-31,2009-01-01,2025-07-08 00:00:00,0.484,0.062,247.860,2.200,0.000,0.000,0.0
2009-02-28,2009-02-01,2025-07-08 00:00:00,3.122,0.120,240.900,12.800,0.000,0.000,18.0
2009-03-31,2009-03-01,2025-07-08 00:00:00,1.470,0.000,241.770,6.000,0.000,0.000,18.0
2009-04-30,2009-04-01,2025-07-08 00:00:00,0.626,0.000,244.870,2.600,0.000,0.000,0.0
2009-05-31,2009-05-01,2025-07-08 00:00:00,1.422,0.102,243.830,5.800,0.000,0.000,19.0
2009-06-30,2009-06-01,2025-07-08 00:00:00,0.140,0.000,243.180,0.600,0.000,0.000,1.0
2009-07-31,2009-07-01,2025-07-08 00:00:00,0.194,0.000,243.750,0.800,0.000,0.000,0.0
2009-08-31,2009-08-01,2025-07-08 00:00:00,0.372,0.356,240.730,2.000,0.000,1.000,0.0
2009-09-30,2009-09-01,2025-07-08 00:00:00,0.416,0.220,244.010,2.000,0.000,0.000,0.0
2009-10-31,2009-10-01,2025-07-08 00:00:00,0.224,0.088,245.190,1.000,0.000,0.000,1.0
2009-11-30,2009-11-01,2025-07-08 00:00:00,0.290,0.080,242.380,1.200,0.000,0.000,0.0
2009-12-31,2009-12-01,2025-07-08 00:00:00,0.418,0.134,243.940,1.800,0.000,0.000,1.0
2010-01-31,2010-01-01,2025-07-08 00:00:00,1.790,0.236,240.650,7.400,0.000,0.000,18.0
2010-02-28,2010-02-01,2025-07-08 00:00:00,0.346,0.000,245.130,1.400,0.000,0.000,1.0
2010-03-31,2010-03-01,2025-07-08 00:00:00,0.370,0.156,240.920,1.600,0.000,1.000,1.0
2010-04-30,2010-04-01,2025-07-08 00:00:00,0.438,0.222,243.660,2.000,0.000,2.000,1.0
2010-05-31,2010-05-01,2025-07-08 00:00:00,0.344,0.108,244.670,1.400,0.000,0.000,1.0
2010-06-30,2010-06-01,2025-07-08 00:00:00,0.326,0.084,243.160,1.400,0.000,0.000,0.0
2010-07-31,2010-07-01,2025-07-08 00:00:00,4.350,0.496,236.320,19.000,31.000,0.000,11.0
2010-08-31,2010-08-01,2025-07-08 00:00:00,0.152,0.000,238.430,0.600,0.000,0.000,1.0
2010-09-30,2010-09-01,2025-07-08 00:00:00,0.746,0.178,242.970,3.400,0.000,0.000,6.0
2010-10-31,2010-10-01,2025-07-08 00:00:00,0.396,0.000,243.540,1.600,0.000,0.000,0.0
2010-11-30,2010-11-01,2025-07-08 00:00:00,1.368,0.08,246.5,5.6,0.0,0.0,1.0

In [ ]:
df.resample('W').last()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,,,
2006-12-17,2006-12-17,2025-07-08 23:59:00,0.276,0.120,244.890,1.200,0.000,1.000,0.0
2006-12-24,2006-12-24,2025-07-08 23:59:00,0.590,0.262,243.850,2.600,0.000,2.000,0.0
2006-12-31,2006-12-31,2025-07-08 23:59:00,2.646,0.236,241.890,11.000,0.000,0.000,0.0
2007-01-07,2007-01-07,2025-07-08 23:59:00,1.384,0.132,243.750,5.600,0.000,1.000,18.0
2007-01-14,2007-01-14,2025-07-08 23:59:00,1.282,0.000,241.500,5.200,0.000,0.000,18.0
...,...,...,...,...,...,...,...,...,...
2010-10-31,2010-10-31,2025-07-08 23:59:00,1.366,0.078,246.26,5.6,0.0,0.0,0.0
2010-11-07,2010-11-07,2025-07-08 23:59:00,0.334,0.062,241.17,1.4,0.0,0.0,1.0
2010-11-14,2010-11-14,2025-07-08 23:59:00,0.228,0.05,242.14,1.0,0.0,0.0,0.0
2010-11-21,2010-11-21,2025-07-08 23:59:00,0.314,0.078,244.07,1.4,0.0,2.0,0.0
2010-11-28,2010-11-26,2025-07-08 21:02:00,0.932,0.0,239.55,3.8,0.0,0.0,0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2075259 entries, 2006-12-16 to 2010-11-26
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   datetime64[ns]
 1   Time                   datetime64[ns]
 2   Global_active_power    object
 3   Global_reactive_power  object
 4   Voltage                object
 5   Global_intensity       object
 6   Sub_metering_1         object
 7   Sub_metering_2         object
 8   Sub_metering_3         float64
dtypes: datetime64[ns](2), float64(1), object(6)
memory usage: 190.6+ MB

In [ ]:
df.index

DatetimeIndex(['2006-12-16', '2006-12-16', '2006-12-16', '2006-12-16',
               '2006-12-16', '2006-12-16', '2006-12-16', '2006-12-16',
               '2006-12-16', '2006-12-16',
               ...
               '2010-11-26', '2010-11-26', '2010-11-26', '2010-11-26',
               '2010-11-26', '2010-11-26', '2010-11-26', '2010-11-26',
               '2010-11-26', '2010-11-26'],
              dtype='datetime64[ns]', name='Datetime', length=2075259, freq=None)

In [ ]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [ ]:
column_group = ['Global_reactive_power', 'Global_active_power','Voltage','Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3']
df[column_group]= df[column_group].replace('?',np.nan)

In [ ]:
df[column_group]= df[column_group].astype('float64')

In [ ]:
df.shape

(2075259, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2075259 entries, 2006-12-16 to 2010-11-26
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   datetime64[ns]
 1   Time                   datetime64[ns]
 2   Global_active_power    float64
 3   Global_reactive_power  float64
 4   Voltage                float64
 5   Global_intensity       float64
 6   Sub_metering_1         float64
 7   Sub_metering_2         float64
 8   Sub_metering_3         float64
dtypes: datetime64[ns](2), float64(7)
memory usage: 190.6 MB

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))
plt.plot(df['Datetime'], df['Global_active_power'], label='Global Active Power', color='blue')
plt.plot(df['Datetime'], df['Global_reactive_power'], label='Global Reactive Power', color='red')
plt.xlabel('Datetime')
plt.ylabel('Power (kW)')
plt.title('Global Active and Reactive Power Over Time')
plt.show()

KeyError: 'Datetime'